### ISSUE TITLE
Python package version mismatch

### ISSUE THREAD

**Issue by musicinmybrain** [DynamicsAndNeuralSystems/catch22#27]
In release 0.4.0, the Python package instead has version 0.3.1.

https://github.com/DynamicsAndNeuralSystems/catch22/blob/2e1a271c6a7437b6a4a754e1adc7e34d7a224c01/wrap_Python/setup.py#L17

https://github.com/DynamicsAndNeuralSystems/catch22/blob/2e1a271c6a7437b6a4a754e1adc7e34d7a224c01/wrap_Python/setup_P3.py#L17

**Comment by benfulcher** [comment]
Thanks! Fixed in 135fb01bbd71c98fea01a7a2612abdca531b44f6
