### ISSUE TITLE
Why catch22-0.2.0 got deleted from pypi

### ISSUE THREAD

**Issue by cahuja1992** [DynamicsAndNeuralSystems/catch22#28]
Ideally, the version should be updated or can be made deprecated. But should not be removed from the repository(PyPi). Can you please upload them back with some new versions tags ?

**Comment by benfulcher** [comment]
I was hoping to encourage people onto the supported version, [`pycatch22`](https://github.com/DynamicsAndNeuralSystems/pycatch22). But I'm open to flagging it as deprecated for users wanting to work on the old version—will look into it.

**Comment by benfulcher** [comment]
I can't see a way on pypi to add the old version back, but it can be accessed/installed manually from this repo. If useful, I could add the old version (v0.2.0) to pycatch22?

**Comment by cahuja1992** [comment]
Yeah, even adding the older version to pycatch22 should serve the purpose. If you can do that, I would be grateful.
Actually, deleting a version broke our system. Therefore, as a practice, nothing should be deleted from pypi.

**Comment by benfulcher** [comment]
Apologies—I'm new to this; in hindsight should definitely have just set it as deprecated.
Strange that there is no reversing this decision… (it seems someone has taken `catch22` for themselves now… :/ https://pypi.org/project/catch22/)

The v0.2.0 version is now `pycatch22`: https://pypi.org/project/pycatch22/0.2.0/ Let me know if you have any issues with this… Apologies again for the issues with your system.

**Comment by cahuja1992** [comment]
Oh, that's strange that someone else took the project name. Anyways, thanks for adding pycatch22/0.2.0.
