### ISSUE TITLE
Please clarify GPL version

### ISSUE THREAD

**Issue by musicinmybrain** [DynamicsAndNeuralSystems/catch22#32]
The files in `MATLAB/` generally have license and copyright statements with “(at your option) any later version” language, so I’m confident they are intended to be, in SPDX terms, [`GPL-3.0-or-later`](https://spdx.org/licenses/GPL-3.0-or-later).

However, the other files in the repository lack comment headers with license and copyright statements, and there doesn’t appear to be any overall license and copyright statement for the repository. The trove classifier for the Python bindings is `License :: OSI Approved :: GNU General Public License v3 (GPLv3)`, which is ambiguous.

Could you please clarify which files are [`GPL-3.0-or-later`](https://spdx.org/licenses/GPL-3.0-or-later) and which, if any, are [`GPL-3.0-only`](https://spdx.org/licenses/GPL-3.0-only)?

**Comment by benfulcher** [comment]
Thanks for this detail, and suggestion to remove ambiguity on this issue. This was @chlubba 's decision, and it seems clearer to use 3-or-later. Do you agree @chlubba ? In which case let me know if you'd like me to action the clarification.

**Comment by chlubba** [comment]
Yes, 3-or-later is fine. Please clarify, thank you.

**Comment by musicinmybrain** [comment]
Thanks!

Note that, while there is no trove classifier that unambiguously indicates `GPL-3.0-only`, there does now exist a [`License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)` trove classifier](https://github.com/pypa/trove-classifiers/blob/866e3e9d600c58c8c7f3495b161b96fdfb50e973/src/trove_classifiers/__init__.py#L286).

**Comment by benfulcher** [comment]
I've stated that 3-or-later is meant in the README. This seems clear, but let me know if, in your opinion, a full license in header of every file is required.

**Comment by musicinmybrain** [comment]
> I've stated that 3-or-later is meant in the README. This seems clear, but let me know if, in your opinion, a full license in header of every file is required.

I can’t speak for any other use cases, or from a lawyerly perspective, but as a Linux distribution packager, it satisfies my needs. Thanks!

**Comment by benfulcher** [comment]
Thanks—appreciate you flagging and helping with this.
