### ISSUE TITLE
What is the shortest time series on which Catch22 could be computed?

### ISSUE THREAD

**Issue by albertoazzari** [DynamicsAndNeuralSystems/catch22#33]
I am interested in understanding whether there exists a minimum length requirement or a lower bound for the length of a time series.

**Comment by benfulcher** [comment]
All of the different statistical estimators will have different length-dependence relationships with their outputs (and depending also on the process). In general, it wouldn't make much sense for a time series shorter than say 20 samples. But even if it's a poor estimate (excepting some algorithms which may break if too short) there is nothing stopping you running the algorithm… You can test this.
